-- AlterTable
ALTER TABLE "Appointment" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "BarberShop" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Service" ALTER COLUMN "id" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "id" DROP DEFAULT;
